### PR TITLE
Restructuring the NMM solution/folders

### PR DESCRIPTION
**Pull request by squid-box**
Before you faint from the number of changed files, additions and deletions, hear me out. I've done some seemingly big, but in reality very small, changes that don't affect how NMM works, just how it's built.

### Output directories
Previously every project built its output to its own **bin** and **obj** folders. This makes cleanup a nightmare if you're trying to pin down some build problem.

**The solution:** I've pointed all build output to the folder `Stage`, which will have a folder for each build config (`Debug`, `Release`) and an `obj` folder with subfolders for the different configs.

I've also removed the MSBuild target from each Game Mode that copied its .dll to `bin\GameModes`, as the output folder for each project points here directly.

As part of this I've also re-written the Setup.iss to grab the relevant files from Stage instead of `bin`. And the installer output will be put in `Stage\Installer`.

### Solution and file system structure
I've also aligned the folder layout with the solution layout, so that all Game Modes are found under the folder Game Mode, instead of in the root of the solution. Also applies to Script Types, Mod Formats, etc.

### CODE REVIEW

**Comment by squid-box** [comment]
As a note, the above conversation with neoh4x0r doesn't actually apply, as I've reverted those changes in 7d0646c.

**Comment by dyslexicanaboko** [comment]
@squid-box I'm confused, you said that you are just restructuring the solution but there are a ton of code changes? Or am I just confused about something, like those commits with code changes are actually from a merge?

**Review by dyslexicanaboko — COMMENTED** [review]
For the NexusLinks.cs isn't that the wrong URL now? You are pointing it to your repo?

**Comment by squid-box** [comment]
I did this change on my side a while back, so there's a mix of merges and rebases before this merge.

But if the link is pointing at my repo I obviously messed this merge up.

I'll review it tonight and probably close this one and try to cherry pick the changes in a new one instead.

**Comment by squid-box** [comment]
Yeah, I'm closing this one and will make a new one tonight, with only cherry-picked commits instead.

**Pull request closed without merging**
