### PR TITLE
Add notice to run VS with admin rights

### PR DESCRIPTION
**Pull request by miere43**
Because trying to compile solution without administrator rights will throw a bunch of errors in your face.

### CODE REVIEW

**Comment by ObsidianMinor** [comment]
I've never received errors while compiling without admin rights. Are you sure it's not a problem with your current setup?

**Comment by miere43** [comment]
@ObsidianMinor, there was a bunch of errors about Antlr that cannot copy it's stuff to some directory and there were errors about projects couln't compile because of dependencies to other projects. I don't know, running VS with admin rights just made everything work with a single hit of "build" button. Actually now I tried running VS without admin rights and everything worked fine.

Maybe it was error in my setup, but I clearly remember how much struggling was done to build project in the past when NMM was on SourceForge, I thought that problems weren't fixed since then.

**Comment by mattiascibien** [comment]
Can you paste here the directory where you checked out the source?

**Comment by WolfMad** [comment]
hi
i think i know what the error the path to the folder where you have the source files has a space in one or more of the folder names fore example  C:\Users\User Name\Documents\Nexus-Mod-Manager-master i think i got this error yesterday

**Pull request closed without merging**
