### PR TITLE
Fix crash when copying file from game mods folder

### PR DESCRIPTION
**Pull request by miere43**
Fixes crash when you are trying to add mod, which is located in current game /Mods folder, to NMM.

### CODE REVIEW

**Comment by DuskDweller** [comment]
Thanks for taking the time to code this, but I was wondering what caused a mod in the Mods folder to not be loaded during the startup phase.
What I mean is that there should be no need to manually add a mod that's already present in the Mods folder, it should already be recognized and added to the list when you start NMM.

**Comment by miere43** [comment]
@DuskDweller, it does recognize mod on startup, but it doesn't do it on runtime. Also, drag-n-dropping any mod from Mods folder, even it is already registered and installed, will still crash NMM.

**Comment by DuskDweller** [comment]
Sorry for the late reply, I was wondering can you test what happens if you keep adding the same mod from the Mods folder again and again, does it keep adding it to the mod list in NMM or it properly recognizes the mod as already present in the list and abort it?

**Comment by miere43** [comment]
@DuskDweller, NMM just crashes if you are adding already registered mod from mods folder (63.1)

```
[D:\Games\Nexus Mod Manager\Skyrim2\Mods\S-Outfit - 7B Bombshell TBBP-67143-.7z] Adding mod from archive.

Tracing an Unhandled Exception:
Exception: 
Message: 
    The process cannot access the file 'D:\Games\Nexus Mod Manager\Skyrim2\Mods\S-Outfit - 7B Bombshell TBBP-67143-.7z' because it is being used by another process.
Full Trace: 
    System.IO.IOException: The process cannot access the file 'D:\Games\Nexus Mod Manager\Skyrim2\Mods\S-Outfit - 7B Bombshell TBBP-67143-.7z' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at Nexus.Client.ModAuthoring.ModBuilder.DoFromArchive(IModFormatRegistry p_mfrFormats, String p_strArchivePath, ConfirmOverwriteCallback p_dlgConfirmOverwrite, String& p_strMessage)
   at Nexus.Client.ModAuthoring.ModBuilder.DoWork(Object[] p_objArgs, String& p_strMessage)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

**Comment by DuskDweller** [comment]
I meant what happens in that situation _after_ applying your fix :)

**Comment by miere43** [comment]
Download Manager just adds that mod with Completed status, no duplicates occur in mod management window, howerer, for some reason you can 'pause' and 'cancel' it in Download Manager window.

**Comment by DuskDweller** [comment]
What if you drag&drop it a few times from the Mods folder does it keep adding it over and over again?

**Comment by miere43** [comment]
No, it doesn't. Why wouldn't you just clone my repo and test it yourself?

**Comment by DuskDweller** [comment]
Because I'm very busy with other stuff and I'd like unbugged code to be pushed to the main repository rather than stuff that'll require fixing :)

**Comment by DuskDweller** [comment]
Thank you very much for the commit and the interest shown in NMM, we managed the issue differently though.

**Pull request closed without merging**
