### PR TITLE
Fixed SecurityException in C# install scripts

### PR DESCRIPTION
**Pull request by ousnius**
Path.GetTempPath() was called in the CSharpScript context due to m_strTempPath being null in the EnvironmentInfo (not filled in the settings file). This caused a SecurityException and failure to install any files from C# install scripts due to the context lacking the permission to read environment variables.

m_strTempPath is now filled when the EnvironmentInfo is created instead of calling Path.GetTempPath() in the TemporaryPath getter.

### CODE REVIEW

**Review by squid-box — APPROVED** [review]
Good investigation and simple fix, I like it!

**Comment by ousnius** [comment]
After this fix I have tested several Fallout NV and (old) Skyrim C# install scripts, and they all installed fine with all script functions doing what they're supposed to.

**Review by dyslexicanaboko — APPROVED** [review]
I recommend getting rid of the class member m_strTempPath all together and just using the property instead. The property can just have a public getter and a private setter for the same effect.

**Review by dyslexicanaboko — APPROVED** [review]

**Comment by ousnius** [comment]
@DuskDweller The merge from master added back the three now unused private members to EnvironmentInfo.

**Pull request merged**
