### PR TITLE
Unified AssemblyInfo

### PR DESCRIPTION
**Pull request by squid-box**
After the critically acclaimed Pull Request hit #481, here comes another back-end upgrade: Reduced the number of shared AssemblyInfo files to one, and pulled in more attributes into it to simplify updating Copyright year and makes sure all game modes are properly versioned as well.

Mainly moving files around in the projects, but also renaming some parts, targeted .NET 4.6 for two older projects.

Maybe biggest thing to look out for is that ProgrammeMetaData has been renamed and put in the Util project instead. I couldn't reference NexusClient.Interface from all projects, due to circular references.

### CODE REVIEW

**Comment by dyslexicanaboko** [comment]
Since we are on the topic of cleanup; you are inspiring me to go through and actually put files where they belong according to their namespaces.

Thanks for the clean up.

Additionally I was wondering if this plugin architecture is actually needed at all, seems like a big waste to me. Tons of projects that honestly can be consolidated so long as the namespaces aren't changed. It can help reduce complications. I can understand if third party dlls were supported but they aren't technically. Unless that was the idea?

**Comment by squid-box** [comment]
Having namespaces correspond to the solution (or other way around) would help with some confusion, especially when trying to follow certain code paths :)

Not sure about the plugin deal, I'm assuming you'd move the game modes from separate projects into folders within NexusClient or something like that? I have absolutely no knowledge on the reasons for the plugin approach, so I can't really answer the question.

**Comment by dyslexicanaboko** [comment]
Sorry I got busy at work, stupid real life getting in the way of my fun. 

Regarding the namespaces, I can do this in small spurts because I don't want to trip up anyone working. It's actually pretty easy to do.

Regarding the plugin stuff - yes, like you said eliminate the separate projects, bring them under the same client and this eliminates a ton of seemingly unnecessary complexity. Of course this may not be the case once someone started working on this transition. I still don't understand what those script files are used for (I haven't looked yet) - so maybe I am over simplifying it. 

Either way doesn't matter one thing at a time.

**Comment by squid-box** [comment]
Given how well my huge change went (#491, #495), I'm also thinking to do things smaller in scope going forward 😆

**Comment by dyslexicanaboko** [comment]
@squid-box the good news is that there isn't a whole parade of people making changes.

**Review by dyslexicanaboko — APPROVED** [review]
Looks good to me

**Comment by DuskDweller** [comment]
Please leave the game's plugin structure intact or face the consequences!!! (a thousand bugs on any game you're not able to test)

**Comment by dyslexicanaboko** [comment]
Yeah? You and what army? I will make all the changes and my pull requests will just never be accepted! I'll show you I will!

Lol - loud and clear thanks for the input.

**Comment by DuskDweller** [comment]
@dyslexicanaboko I fixed 0.65.8 release notes on Github giving credits to squid-box for your work.

**Comment by dyslexicanaboko** [comment]
It's all good man :)

**Pull request merged**
