### PR TITLE
FEATURE: User is able to download the latest version of the selected mod from NMM client

### PR DESCRIPTION
**Pull request by GrimSmiler**
Steps to reproduce:
1) Select an outdated mod
2) Open context menu of the mod (right click on the selected mod)
3) Select "Download new version"

image

Implemented feature:
- adds a latest mod version to download.
- does not initiate upgrading of a mod automatically. This has to be done by user himself (to avoid breaking game saves/setup/files).
- get the latest specified version. Cannot distinguish between multiple variations of the same version.

### CODE REVIEW

**Comment by GrimSmiler** [comment]
@DuskDweller Hi!
Sorry to bother, would You have some time to look at this? Would You approve a pull request or am missing something?

**Comment by DuskDweller** [comment]
Hi @GrimSmiler thank you very much for taking the time developing this feature for NMM, sadly while this could be extremely helpful it's against the current Nexus' policy and also mod authors require users to check their mod page to download mod updates cause often it isn't just a "Uninstall Old, Install New" process (save for texture mods).

Last but not least I'm no longer affiliated with the Nexus so I'm helping maintaining the NMM source until it is needed just out of passion.

**Comment by GrimSmiler** [comment]
oh well :(
I guess i can just keep it in my own fork.
Thanks for the update and sorry for bothering :(

**Comment by DuskDweller** [comment]
Absolutely no bother, just sorry I couldn't merge something you clearly spent a good time on.

**Pull request closed without merging**
